## Notebook for testing data hanlders

First do the necessary imports

In [1]:
import datetime
import logging
import sys
import numpy as np

#sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')
sys.path.append('/media/controlslab/DATA/Projects')


from ann_framework.data_handlers.data_handler_CMAPSS import CMAPSSDataHandler
from ann_framework.data_handlers.data_handler_MNIST import MNISTDataHandler
from ann_framework.data_handlers.data_handler_CIFAR10 import CIFAR10DataHandler
from ann_framework.data_handlers.data_handler_Oscillator import OscillatorDataHandler
from ann_framework.data_handlers.data_handler_NIH import NIHDataHandler

Using TensorFlow backend.


### CMAPSS Data Handler Test

In [2]:
#Selected as per CNN paper
features = ['T2', 'T24', 'T30', 'T50', 'P2', 'P15', 'P30', 'Nf', 'Nc', 'epr', 'Ps30', 'phi', 'NRf', 'NRc', 
                     'BPR', 'farB', 'htBleed', 'Nf_dmd', 'PCNfR_dmd', 'W31', 'W32']
selected_indices = np.array([2, 3, 4, 7, 8, 9, 11, 12, 13, 14, 15, 17, 20, 21])
selected_features = list(features[i] for i in selected_indices-1)
data_folder = '../../NASA_RUL_-CMAPS-/CMAPSSData'

window_size = 30
window_stride = 1
max_rul = 125

dHandler_cmaps = CMAPSSDataHandler(data_folder, 1, selected_features, max_rul, window_size, window_stride)
dHandler_cmaps.data_scaler = None
dHandler_cmaps.load_data(unroll=True, verbose=1, cross_validation_ratio=0.2)
dHandler_cmaps.print_data()

Loading data for dataset 1 with window_size of 30, stride of 1 and maxRUL of 125. Cros-Validation ratio 0.2
Loading data from file and computing dataframes
Printing shapes

Training data (X, y)
(14397, 420)
(14397, 1)
Cross-Validation data (X, y)
(20, 420)
(20, 1)
Testing data (X, y)
(100, 420)
(100, 1)
Printing first 5 elements

Training data (X, y)
[[ 641.82   1589.7    1400.6    ...  390.       39.05     23.411 ]
 [ 642.15   1591.82   1403.14   ...  392.       38.94     23.3353]
 [ 642.35   1587.99   1404.2    ...  392.       39.02     23.4999]
 [ 642.35   1582.79   1401.87   ...  392.       38.83     23.3506]
 [ 642.37   1582.85   1406.22   ...  392.       38.81     23.3092]]
[[125.]
 [125.]
 [125.]
 [125.]
 [125.]]
Cross-Validation data (X, y)
[[ 642.36   1588.29   1403.56   ...  394.       38.8      23.3428]
 [ 642.61   1587.72   1397.75   ...  392.       38.76     23.298 ]
 [ 643.01   1591.12   1408.75   ...  395.       38.71     23.115 ]
 [ 642.52   1590.76   1402.33   ...  392

### MNIST Data Handler Test

In [3]:
dHandler_mnist = MNISTDataHandler()
dHandler_mnist.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_mnist.print_data()

example = dHandler_mnist.X_train[0]
print(example.shape)
print(example)

Loading data. Cross-Validation ratio 0.2
Printing shapes

Training data (X, y)
(48000, 28, 28)
(48000, 10)
Cross-Validation data (X, y)
(12000, 28, 28)
(12000, 10)
Testing data (X, y)
(10000, 28, 28)
(10000, 10)
Printing first 5 elements

Training data (X, y)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...


/home/controlslab/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


### CIFAR10 DataHandler

In [ ]:
dHandler_cifar10 = CIFAR10DataHandler()
dHandler_cifar10.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_cifar10.print_data()

example = dHandler_cifar10.X_train[0]
print(example.shape)
print(example)

### Oscillator DataHandler

In [ ]:
dHandler_oscillator = OscillatorDataHandler()
dHandler_oscillator.load_data(verbose=1, cross_validation_ratio=0.2, x=[0,0], boundaries=[2,7], n=[2,3])
dHandler_oscillator.print_data()

#example = dHandler_cifar10.X_train[0]
#print(example.shape)
#print(example)

### NIH DataHandler

In [ ]:
# import os
# print(os.listdir("../../NIHdata/data"))

data_file = '../../NIHdata/data/Data_Entry_2017.csv'
data_folder = '../../NIHdata/data/'
dHandler_NIH = NIHDataHandler(data_file, data_folder)
dHandler_NIH.load_data(verbose = 0, cross_validation_ratio = 0.20, prune_threshold=1000, number_samples=5000)
# dHandler_NIH.print_data()
dHandler_NIH.show_img()