## Notebook for testing data hanlders

First do the necessary imports

In [1]:
import datetime
import logging
import sys
import numpy as np

#sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')
sys.path.append('/media/controlslab/DATA/Projects')


from ann_framework.data_handlers.data_handler_CMAPSS import CMAPSSDataHandler
from ann_framework.data_handlers.data_handler_MNIST import MNISTDataHandler
from ann_framework.data_handlers.data_handler_CIFAR10 import CIFAR10DataHandler
from ann_framework.data_handlers.data_handler_Oscillator import OscillatorDataHandler
from ann_framework.data_handlers.data_handler_NIH import NIHDataHandler

Using TensorFlow backend.


### CMAPSS Data Handler Test

In [2]:
#Selected as per CNN paper
features = ['T2', 'T24', 'T30', 'T50', 'P2', 'P15', 'P30', 'Nf', 'Nc', 'epr', 'Ps30', 'phi', 'NRf', 'NRc', 
                     'BPR', 'farB', 'htBleed', 'Nf_dmd', 'PCNfR_dmd', 'W31', 'W32']
selected_indices = np.array([2, 3, 4, 7, 8, 9, 11, 12, 13, 14, 15, 17, 20, 21])
selected_features = list(features[i] for i in selected_indices-1)
data_folder = '../../NASA_RUL_-CMAPS-/CMAPSSData'

window_size = 30
window_stride = 1
max_rul = 125

dHandler_cmaps = CMAPSSDataHandler(data_folder, 1, selected_features, max_rul, window_size, window_stride)
dHandler_cmaps.data_scaler = None
dHandler_cmaps.load_data(unroll=True, verbose=1, cross_validation_ratio=0.2)
dHandler_cmaps.print_data()

Loading data for dataset 1 with window_size of 30, stride of 1 and maxRUL of 125. Cros-Validation ratio 0.2
Loading data from file and computing dataframes
Printing shapes

Training data (X, y)
(14037, 420)
(14037, 1)
Cross-Validation data (X, y)
(20, 420)
(20, 1)
Testing data (X, y)
(100, 420)
(100, 1)
Printing first 5 elements

Training data (X, y)
[[ 641.89   1583.84   1391.28   ...  391.       39.1      23.3985]
 [ 641.82   1587.05   1393.13   ...  391.       39.17     23.4154]
 [ 641.55   1588.32   1398.96   ...  390.       38.97     23.4006]
 [ 641.68   1584.15   1396.08   ...  392.       39.01     23.4434]
 [ 641.73   1579.03   1402.52   ...  390.       38.87     23.4571]]
[[125.]
 [125.]
 [125.]
 [125.]
 [125.]]
Cross-Validation data (X, y)
[[ 642.77   1588.49   1403.62   ...  394.       38.9      23.3121]
 [ 642.33   1589.6    1396.89   ...  392.       38.91     23.3109]
 [ 642.55   1587.69   1409.     ...  394.       38.68     23.3456]
 [ 642.83   1595.37   1412.12   ...  396

### MNIST Data Handler Test

In [3]:
dHandler_mnist = MNISTDataHandler()
dHandler_mnist.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_mnist.print_data()

example = dHandler_mnist.X_train[0]
print(example.shape)
print(example)

TypeError: __init__() missing 1 required positional argument: 'data_scaler'

### CIFAR10 DataHandler

In [ ]:
dHandler_cifar10 = CIFAR10DataHandler()
dHandler_cifar10.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_cifar10.print_data()

example = dHandler_cifar10.X_train[0]
print(example.shape)
print(example)

### Oscillator DataHandler

In [ ]:
dHandler_oscillator = OscillatorDataHandler()
dHandler_oscillator.load_data(verbose=1, cross_validation_ratio=0.2, x=[0,0], delta_x=[5,5], n=[50,50])
dHandler_oscillator.print_data()

#example = dHandler_cifar10.X_train[0]
#print(example.shape)
#print(example)

# NIH DataHandler

In [2]:
# import os
# print(os.listdir("../../NIHdata/data"))

data_file = '../../NIHdata/data/Data_Entry_2017.csv'
dHandler_NIH = NIHDataHandler(data_file)
dHandler_NIH.load_data(verbose = 0, cross_validation_ratio = 0.25, normalize = 1)
dHandler_NIH.print_data()

Scans found: 112120 , Total Headers 112120
All Labels (14): ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Effusion', 'Emphysema', 'Fibrosis', 'Hernia', 'Infiltration', 'Mass', 'Nodule', 'Pleural_Thickening', 'Pneumonia', 'Pneumothorax']
Clean Labels (13) [('Atelectasis', 11559), ('Cardiomegaly', 2776), ('Consolidation', 4667), ('Edema', 2303), ('Effusion', 13317), ('Emphysema', 2516), ('Fibrosis', 1686), ('Infiltration', 19894), ('Mass', 5782), ('Nodule', 6331), ('Pleural_Thickening', 3385), ('Pneumonia', 1431), ('Pneumothorax', 5302)]
train 30000 validation 10000
## Ignore next message from keras, values are replaced anyways
Found 0 images belonging to 0 classes.
Reinserting dataframe: 30000 images
## Ignore next message from keras, values are replaced anyways
Found 0 images belonging to 0 classes.
Reinserting dataframe: 10000 images
## Ignore next message from keras, values are replaced anyways
Found 0 images belonging to 0 classes.
Reinserting dataframe: 10000 images
Pr