## Notebook for testing data hanlders

First do the necessary imports

In [1]:
import datetime
import logging
import sys
import numpy as np

sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')
#sys.path.append('/media/controlslab/DATA/Projects')


from ann_framework.data_handlers.data_handler_CMAPSS import CMAPSSDataHandler
from ann_framework.data_handlers.data_handler_MNIST import MNISTDataHandler
from ann_framework.data_handlers.data_handler_CIFAR10 import CIFAR10DataHandler
from ann_framework.data_handlers.data_handler_Grid import GridDataHandler
from ann_framework.data_handlers.data_handler_NIH import NIHDataHandler

Using TensorFlow backend.


### CMAPSS Data Handler Test

In [ ]:
#Selected as per CNN paper
features = ['T2', 'T24', 'T30', 'T50', 'P2', 'P15', 'P30', 'Nf', 'Nc', 'epr', 'Ps30', 'phi', 'NRf', 'NRc', 
                     'BPR', 'farB', 'htBleed', 'Nf_dmd', 'PCNfR_dmd', 'W31', 'W32']
selected_indices = np.array([2, 3, 4, 7, 8, 9, 11, 12, 13, 14, 15, 17, 20, 21])
selected_features = list(features[i] for i in selected_indices-1)
data_folder = '../../NASA_RUL_-CMAPS-/CMAPSSData'

window_size = 30
window_stride = 1
max_rul = 125

dHandler_cmaps = CMAPSSDataHandler(data_folder, 1, selected_features, max_rul, window_size, window_stride)
dHandler_cmaps.data_scaler = None
dHandler_cmaps.load_data(unroll=True, verbose=1, cross_validation_ratio=0.2)
dHandler_cmaps.print_data()

### MNIST Data Handler Test

In [ ]:
dHandler_mnist = MNISTDataHandler()
dHandler_mnist.load_data(verbose=1, cross_validation_ratio=0.2, unroll=False)
dHandler_mnist.print_data()

example = dHandler_mnist.X_train[0]
print(example.shape)
print(example)

### CIFAR10 DataHandler

In [ ]:
dHandler_cifar10 = CIFAR10DataHandler()
dHandler_cifar10.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_cifar10.print_data()

example = dHandler_cifar10.X_train[0]
print(example.shape)
print(example)

### Oscillator DataHandler

In [2]:
#1-D problem


dHandler_grid = GridDataHandler()
dHandler_grid.load_data(verbose=1, cross_validation_ratio=0.2, boundaries=[[0,1], [0,1], [0,1]], n=[5, 5, 5])
dHandler_grid.print_data()

#example = dHandler_cifar10.X_train[0]
#print(example.shape)
#print(example)

[[0, 1], [0, 1], [0, 1]]
[5, 5, 5]
Loading data. Cros-Validation ratio 0.2
Printing shapes

Training data (X, y)
(89, 3)
(89, 1)
Cross-Validation data (X, y)
(23, 3)
(23, 1)
Testing data (X, y)
(13, 3)
(13, 1)
Printing first 5 elements

Training data (X, y)
[[0.25 0.   0.5 ]
 [1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.5  0.25 0.5 ]
 [0.25 0.75 1.  ]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Cross-Validation data (X, y)
[[0.   1.   0.  ]
 [0.   0.25 0.  ]
 [1.   0.   1.  ]
 [0.   1.   1.  ]
 [0.5  0.75 0.5 ]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Testing data (X, y)
[[0.25 1.   0.  ]
 [0.25 0.   0.  ]
 [1.   0.75 0.5 ]
 [0.   0.5  1.  ]
 [0.25 0.   0.75]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


/Users/davidlaredorazo/anaconda/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


### NIH DataHandler

In [ ]:
# import os
# print(os.listdir("../../NIHdata/data"))

data_file = '../../NIHdata/data/Data_Entry_2017.csv'
data_folder = '../../NIHdata/data/'
dHandler_NIH = NIHDataHandler(data_file, data_folder, multi_labels=False)
dHandler_NIH.load_data(verbose = 0, cross_validation_ratio = 0.20, prune_threshold=1000, number_samples=5000)
# dHandler_NIH.print_data()
#dHandler_NIH.show_img()

In [ ]:
a = np.random.random([10, ])
b = np.random.random([10, ])

np.sum(a-b)

In [ ]:
a = np.random.random([10, ])
print(a)
a[[1,4,5,6]]
a[[]] = 0
print(a)