## Notebook for testing data hanlders

First do the necessary imports

In [1]:
import datetime
import logging
import sys
import numpy as np

sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')


from ann_framework.data_handlers.data_handler_CMAPS import CMAPSDataHandler
from ann_framework.data_handlers.data_handler_MNIST import MNISTDataHandler
from ann_framework.data_handlers.data_handler_CIFAR10 import CIFAR10DataHandler

Using TensorFlow backend.


### CMAPSS Data Handler Test

In [2]:
#Selected as per CNN paper
features = ['T2', 'T24', 'T30', 'T50', 'P2', 'P15', 'P30', 'Nf', 'Nc', 'epr', 'Ps30', 'phi', 'NRf', 'NRc', 
                     'BPR', 'farB', 'htBleed', 'Nf_dmd', 'PCNfR_dmd', 'W31', 'W32']
selected_indices = np.array([2, 3, 4, 7, 8, 9, 11, 12, 13, 14, 15, 17, 20, 21])
selected_features = list(features[i] for i in selected_indices-1)
data_folder = '../../NASA_RUL_(CMAPS)/CMAPSSData'

window_size = 30
window_stride = 1
max_rul = 125

dHandler_cmaps = CMAPSDataHandler(data_folder, 1, selected_features, max_rul, window_size, window_stride)
dHandler_cmaps.data_scaler = None
dHandler_cmaps.load_data(unroll=True, verbose=1, cross_validation_ratio=0.2)
dHandler_cmaps.print_data()

Loading data for dataset 1 with window_size of 30, stride of 1 and maxRUL of 125. Cros-Validation ratio 0.2
Loading data from file and computing dataframes
Printing shapes

Training data (X, y)
(14324, 420)
(14324, 1)
Cross-Validation data (X, y)
(20, 420)
(20, 1)
Testing data (X, y)
(100, 420)
(100, 1)
Printing first 5 elements

Training data (X, y)
[[ 641.82   1589.7    1400.6    ...  390.       39.05     23.411 ]
 [ 642.15   1591.82   1403.14   ...  392.       38.94     23.3353]
 [ 642.35   1587.99   1404.2    ...  392.       39.02     23.4999]
 [ 642.35   1582.79   1401.87   ...  392.       38.83     23.3506]
 [ 642.37   1582.85   1406.22   ...  392.       38.81     23.3092]]
[[125.]
 [125.]
 [125.]
 [125.]
 [125.]]
Cross-Validation data (X, y)
[[ 643.19   1589.76   1407.19   ...  395.       38.67     23.3089]
 [ 641.82   1590.96   1407.83   ...  393.       38.99     23.4565]
 [ 642.97   1591.     1413.93   ...  394.       38.88     23.149 ]
 [ 642.9    1585.88   1411.13   ...  394

### MNIST Data Handler Test

In [3]:
dHandler_mnist = MNISTDataHandler()
dHandler_mnist.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_mnist.print_data()

example = dHandler_mnist.X_train[0]
print(example.shape)
print(example)

Loading data. Cros-Validation ratio 0.2
Printing shapes

Training data (X, y)
(48000, 784)
(48000, 10)
Cross-Validation data (X, y)
(12000, 784)
(12000, 10)
Testing data (X, y)
(10000, 784)
(10000, 10)
Printing first 5 elements

Training data (X, y)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Cross-Validation data (X, y)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Testing data (X, y)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0.

/Users/davidlaredorazo/anaconda/envs/tensorflow/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2010: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


### CIFAR10 DataHandler

In [4]:
dHandler_cifar10 = CIFAR10DataHandler()
dHandler_cifar10.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_cifar10.print_data()

example = dHandler_cifar10.X_train[0]
print(example.shape)
print(example)

Loading data. Cros-Validation ratio 0.2


/Users/davidlaredorazo/anaconda/envs/tensorflow/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2010: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


Printing shapes

Training data (X, y)
(40000, 3072)
(40000, 10)
Cross-Validation data (X, y)
(10000, 3072)
(10000, 10)
Testing data (X, y)
(10000, 3072)
(10000, 10)
Printing first 5 elements

Training data (X, y)
[[0.43529412 0.61960787 0.9647059  ... 0.52156866 0.69411767 0.972549  ]
 [0.9372549  0.8980392  0.827451   ... 0.81960785 0.7137255  0.5411765 ]
 [0.42745098 0.43137255 0.40784314 ... 0.31764707 0.26666668 0.1764706 ]
 [0.9137255  0.9137255  0.8745098  ... 0.05882353 0.21568628 0.30980393]
 [0.7607843  0.7607843  0.7372549  ... 0.3882353  0.36862746 0.33333334]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Cross-Validation data (X, y)
[[0.3882353  0.29803923 0.23137255 ... 0.5137255  0.46666667 0.43137255]
 [0.10980392 0.23137255 0.12156863 ... 0.3254902  0.23137255 0.14117648]
 [0.49803922 0.627451   0.60784316 ... 0.75686276 0.74509805 0.7490196 ]
 [0.282