## Notebook for testing data hanlders

First do the necessary imports

In [1]:
import datetime
import logging
import sys
import numpy as np
import random

sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')
#sys.path.append('/media/controlslab/DATA/Projects')

from sklearn.preprocessing import OneHotEncoder


from ann_framework.data_handlers.data_handler_CMAPSS import CMAPSSDataHandler
from ann_framework.data_handlers.data_handler_MNIST import MNISTDataHandler
from ann_framework.data_handlers.data_handler_CIFAR10 import CIFAR10DataHandler
from ann_framework.data_handlers.data_handler_Grid import GridDataHandler
from ann_framework.data_handlers.data_handler_NIH import NIHDataHandler
from ann_framework.data_handlers.data_handler_DAMADICS import DamadicsDataHandler

Using TensorFlow backend.


### CMAPSS Data Handler Test

In [ ]:
#Selected as per CNN paper
features = ['T2', 'T24', 'T30', 'T50', 'P2', 'P15', 'P30', 'Nf', 'Nc', 'epr', 'Ps30', 'phi', 'NRf', 'NRc', 
                     'BPR', 'farB', 'htBleed', 'Nf_dmd', 'PCNfR_dmd', 'W31', 'W32']
selected_indices = np.array([2, 3, 4, 7, 8, 9, 11, 12, 13, 14, 15, 17, 20, 21])
selected_features = list(features[i] for i in selected_indices-1)
data_folder = '../../NASA_RUL_(CMAPS)/CMAPSSData'

window_size = 30
window_stride = 1
max_rul = 125

dHandler_cmaps = CMAPSSDataHandler(data_folder, 1, selected_features, max_rul, window_size, window_stride)
dHandler_cmaps.data_scaler = None
dHandler_cmaps.load_data(unroll=True, verbose=1, cross_validation_ratio=0.2)
dHandler_cmaps.print_data()

### MNIST Data Handler Test

In [ ]:
dHandler_mnist = MNISTDataHandler()
dHandler_mnist.load_data(verbose=1, cross_validation_ratio=0.2, unroll=False)
dHandler_mnist.print_data()

example = dHandler_mnist.X_train[0]
print(example.shape)
print(example)

### CIFAR10 DataHandler

In [ ]:
dHandler_cifar10 = CIFAR10DataHandler()
dHandler_cifar10.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_cifar10.print_data()

example = dHandler_cifar10.X_train[0]
print(example.shape)
print(example)

### DAMADICS DataHandler

In [2]:
start_date = datetime.datetime(2018, 2, 14, 18, 59, 20)
date2 = datetime.datetime(2018, 2, 14, 18, 59, 20)
time_delta = datetime.timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=1, hours=0, weeks=0)
end_time = start_date + 1001*time_delta #get the first 300 instances

features = ['externalControllerOutput', 'undisturbedMediumFlow', 'pressureValveInlet', 
            'pressureValveOutlet', 'mediumTemperature', 'rodDisplacement', 'disturbedMediumFlow', 
           'selectedFault', 'faultType', 'faultIntensity']

selected_indices = np.array([1,2,3,4,5,6])
selected_features = list(features[i] for i in selected_indices-1)

#Does not work for sequence sizes larger than 1 given the way I'm generating the test data. 
#Need to properly define what the test data is going to be like.
window_size = 1
window_stride = 1

dHandlder_valve = DamadicsDataHandler(selected_features, window_size, window_stride)
dHandlder_valve.connect_to_db('readOnly', '_readOnly2019', '169.236.181.40', 'damadics')

Connection to mysql+mysqldb://readOnly:_readOnly2019@169.236.181.40/damadics successfull


In [12]:
dHandlder_valve.load_data(start_date, end_time, unroll=True, verbose=1)
dHandlder_valve.print_data(print_top=True)

#One hot encoding
#cat = np.arange(1,5)
#encoder = OneHotEncoder(categories=[cat])
#encoder = OneHotEncoder(categories=[np.arange(1,21)])
#output_one_hot_matrix = encoder.fit_transform(self._y.reshape(-1, 1)).toarray()
#print(encoder.categories_)
#print(self._y[:5])
#print(output_one_hot_matrix[:5, :])
#output_one_hot_matrix = self.one_hot_encode(self._df.shape[0])
#output_one_hot_matrix = encoder.fit_transform(self._y.reshape(-1, 1)).toarray()
#self._y = encoder.fit_transform(self._y.reshape(-1, 1)).toarray()


Loading data for DAMADICS with window_size of 1, stride of 1. Cros-Validation ratio 0
Loading data from memory
data splitting: 0:00:00.000023
Printing shapes

Training data (X, y)
(256, 6)
(256, 1)
Testing data (X, y)
(1, 6)
(1, 1)
Printing first 5 elements

Training data (X, y)
[[0.5      0.87684  0.650832 0.214553 0.00159  1.      ]
 [0.366043 0.850576 0.643717 0.215373 0.369939 1.      ]
 [0.732444 0.849537 0.647472 0.214781 0.732446 0.222181]
 [0.257854 0.849203 0.648064 0.214384 0.239649 0.99759 ]
 [0.659356 0.848475 0.654271 0.214159 0.67503  0.283687]]
[[20.]
 [20.]
 [20.]
 [20.]
 [20.]]
Testing data (X, y)
[[0.366043 0.849582 0.65491  0.213536 0.500932 0.682573]]
[[1.]]


### Oscillator DataHandler

In [ ]:
#1-D problem

dHandler_grid = GridDataHandler()
dHandler_grid.load_data(verbose=1, cross_validation_ratio=0.2, boundaries=[[0,1], [0,1], [0,1]], n=[5, 5, 5])
dHandler_grid.print_data()

### NIH DataHandler

In [ ]:
# import os
# print(os.listdir("../../NIHdata/data"))

data_file = '../../NIHdata/data/Data_Entry_2017.csv'
data_folder = '../../NIHdata/data/'
dHandler_NIH = NIHDataHandler(data_file, data_folder, multi_labels=False)
dHandler_NIH.load_data(verbose = 0, cross_validation_ratio = 0.20, prune_threshold=1000, number_samples=5000)
# dHandler_NIH.print_data()
#dHandler_NIH.show_img()

In [ ]:
a = np.random.random([10, ])
b = np.random.random([10, ])

np.sum(a-b)

In [ ]:
a = np.random.random([10, ])
print(a)
a[[1,4,5,6]]
a[[]] = 0
print(a)