## Notebook for testing data hanlders

First do the necessary imports

In [2]:
import datetime
import logging
import sys
import numpy as np

#sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')
sys.path.append('/media/controlslab/DATA/Projects')


from ann_framework.data_handlers.data_handler_CMAPSS import CMAPSSDataHandler
from ann_framework.data_handlers.data_handler_MNIST import MNISTDataHandler
from ann_framework.data_handlers.data_handler_CIFAR10 import CIFAR10DataHandler
from ann_framework.data_handlers.data_handler_Oscillator import OscillatorDataHandler

Using TensorFlow backend.


### CMAPSS Data Handler Test

In [4]:
#Selected as per CNN paper
features = ['T2', 'T24', 'T30', 'T50', 'P2', 'P15', 'P30', 'Nf', 'Nc', 'epr', 'Ps30', 'phi', 'NRf', 'NRc', 
                     'BPR', 'farB', 'htBleed', 'Nf_dmd', 'PCNfR_dmd', 'W31', 'W32']
selected_indices = np.array([2, 3, 4, 7, 8, 9, 11, 12, 13, 14, 15, 17, 20, 21])
selected_features = list(features[i] for i in selected_indices-1)
data_folder = '../../NASA_RUL_-CMAPS-/CMAPSSData'

window_size = 30
window_stride = 1
max_rul = 125

dHandler_cmaps = CMAPSSDataHandler(data_folder, 1, selected_features, max_rul, window_size, window_stride)
dHandler_cmaps.data_scaler = None
dHandler_cmaps.load_data(unroll=True, verbose=1, cross_validation_ratio=0.2)
dHandler_cmaps.print_data()

Loading data for dataset 1 with window_size of 30, stride of 1 and maxRUL of 125. Cros-Validation ratio 0.2
Loading data from file and computing dataframes
Printing shapes

Training data (X, y)
(14077, 420)
(14077, 1)
Cross-Validation data (X, y)
(20, 420)
(20, 1)
Testing data (X, y)
(100, 420)
(100, 1)
Printing first 5 elements

Training data (X, y)
[[ 641.89   1583.84   1391.28   ...  391.       39.1      23.3985]
 [ 641.82   1587.05   1393.13   ...  391.       39.17     23.4154]
 [ 641.55   1588.32   1398.96   ...  390.       38.97     23.4006]
 [ 641.68   1584.15   1396.08   ...  392.       39.01     23.4434]
 [ 641.73   1579.03   1402.52   ...  390.       38.87     23.4571]]
[[125.]
 [125.]
 [125.]
 [125.]
 [125.]]
Cross-Validation data (X, y)
[[ 642.01   1586.11   1397.51   ...  391.       38.93     23.3583]
 [ 642.41   1584.72   1397.68   ...  392.       38.77     23.4928]
 [ 642.79   1583.23   1407.15   ...  393.       38.7      23.3114]
 [ 642.35   1584.13   1405.1    ...  395

### MNIST Data Handler Test

In [ ]:
dHandler_mnist = MNISTDataHandler()
dHandler_mnist.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_mnist.print_data()

example = dHandler_mnist.X_train[0]
print(example.shape)
print(example)

### CIFAR10 DataHandler

In [ ]:
dHandler_cifar10 = CIFAR10DataHandler()
dHandler_cifar10.load_data(verbose=1, cross_validation_ratio=0.2)
dHandler_cifar10.print_data()

example = dHandler_cifar10.X_train[0]
print(example.shape)
print(example)

### Oscillator DataHandler

In [2]:
dHandler_oscillator = OscillatorDataHandler()
dHandler_oscillator.load_data(verbose=1, cross_validation_ratio=0.2, x=[0,0], delta_x=[5,5], n=[50,50])
dHandler_oscillator.print_data()

#example = dHandler_cifar10.X_train[0]
#print(example.shape)
#print(example)

Loading data. Cros-Validation ratio 0.2
Printing shapes

Training data (X, y)
(7200, 2)
(7200, 1)
Cross-Validation data (X, y)
(1800, 2)
(1800, 1)
Testing data (X, y)
(1000, 2)
(1000, 1)
Printing first 5 elements

Training data (X, y)
[[ 2.97979798  4.09090909]
 [-3.58585859  1.16161616]
 [-0.05050505  4.6969697 ]
 [ 4.19191919  3.68686869]
 [ 2.07070707  4.6969697 ]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Cross-Validation data (X, y)
[[-0.15151515 -0.65656566]
 [ 1.16161616  0.85858586]
 [-1.26262626 -3.48484848]
 [ 3.78787879 -0.85858586]
 [ 3.18181818 -4.49494949]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Testing data (X, y)
[[-2.87878788  3.38383838]
 [-0.85858586 -1.96969697]
 [-1.86868687  3.18181818]
 [ 0.45454545 -1.36363636]
 [-4.7979798   4.6969697 ]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


/Users/davidlaredorazo/anaconda/envs/tensorflow/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2010: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


# NIH DataHandler

In [2]:
data_file = '../../NIHdata/data/Data_Entry_2017.csv'
dHandler_NIH = NIHDataHandler(data_file)
dHandler_NIH.load_data(verbose = 0, cross_validation_ratio = 0.25, normalize = 1)

Scans found: 0 , Total Headers 112120
All Labels (14): ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Effusion', 'Emphysema', 'Fibrosis', 'Hernia', 'Infiltration', 'Mass', 'Nodule', 'Pleural_Thickening', 'Pneumonia', 'Pneumothorax']
Clean Labels (13) [('Atelectasis', 11559), ('Cardiomegaly', 2776), ('Consolidation', 4667), ('Edema', 2303), ('Effusion', 13317), ('Emphysema', 2516), ('Fibrosis', 1686), ('Infiltration', 19894), ('Mass', 5782), ('Nodule', 6331), ('Pleural_Thickening', 3385), ('Pneumonia', 1431), ('Pneumothorax', 5302)]
train 30000 validation 10000


TypeError: expected str, bytes or os.PathLike object, not NoneType